version: 0.2

eb_codebuild_settings:
  CodeBuildServiceRole: arn:aws:codebuild:us-east-1:655133093432:project/CloudieDemo
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/amazonlinux2-aarch64-standard:2.0
  Timeout: 10

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python3.7 -m venv ~/.venv
      - source ~/.venv/bin/activate
      - make install
      - make lint

  build:
    commands:
      - make deploy
